### PR TITLE
support UVerb + correctly bound Fragment instance for older servant versions

### PR DESCRIPTION
**Pull request by lehmacdj**
Upstreaming a change we've been using at SimSpace for a while to support the `UVerb` combinator. Cherry picked / polished the commit referenced below onto the latest master here.

I additionally added CPP around the fragment instance as that would theoretically break this library with servant versions `<0.18.2`.

The original change is here (you shouldn't need to look at it though): https://github.com/Simspace/servant-ekg/commit/467ac18f19b9b4ec854315c82a68f25ceee8a967

### CODE REVIEW

**Comment by arianvp** [comment]
Thanks! This looks good. I have no idea why Github Actions stopped triggering though....

**Review by arianvp — APPROVED** [review]

**Review by arianvp — APPROVED** [review]

**Comment by arianvp** [comment]
I think it's not working because of this? https://github.com/haskell-servant/servant-ekg/issues/27

**Comment by arianvp** [comment]
oh.. https://www.githubstatus.com/ Github Actions is down.  maybe that's the issue.

**Comment by lehmacdj** [comment]
Fixed the merge conflict. It looks like you need to approve running the workflow now, I'm guessing that's what happened before too, but maybe GitHub lost track of the request after a while.

**Comment by howabouthis** [comment]
@lehmacdj @arianvp 

Is there still something blocking this from getting merged?

**Comment by lehmacdj** [comment]
Not from me, this looks good to merge to me

**Comment by lehmacdj** [comment]
@arianvp can you merge this please?

**Comment by arianvp** [comment]
Sorry for the delay. I haven't been actively using Haskell for quite a while. Patch still looks good and still cleanly applies so am merging.

**Pull request merged**
